project:
  type: website

website:
  title: "Cara's Sandbox"
  # This tells Quarto which page is the home page
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
